// ─── Auth ────────────────────────────────────────────────────────────────────
export const AUTHORIZED_USERS = [
  { email: "erion@example.com", password: "admin123", name: "Erion", role: "Admin" },
  { email: "team@example.com", password: "team2026", name: "Team Member", role: "Staff" },
];

// ─── Status config (used by frontend pages) ──────────────────────────────────
export const STATUS_CONFIG = {
  pending:    { label: "Pending",    color: "#F59E0B", bg: "#FEF3C7" },
  processing: { label: "Processing", color: "#3B82F6", bg: "#DBEAFE" },
  "on-hold":  { label: "On Hold",   color: "#8B5CF6", bg: "#EDE9FE" },
  completed:  { label: "Completed", color: "#10B981", bg: "#D1FAE5" },
  cancelled:  { label: "Cancelled", color: "#EF4444", bg: "#FEE2E2" },
  refunded:   { label: "Refunded",  color: "#6B7280", bg: "#F3F4F6" },
};

export const STATUS_FLOW = {
  pending:    ["processing", "on-hold", "cancelled"],
  processing: ["completed", "on-hold", "cancelled"],
  "on-hold":  ["processing", "cancelled"],
  completed:  ["refunded"],
  cancelled:  [],
  refunded:   [],
};

// ─── Simple mock orders (used by existing frontend pages) ─────────────────────
export const MOCK_ORDERS = [
  { id: 1042, customer: "Lena Müller", email: "lena@example.com", items: [{ name: "Organic Face Serum", qty: 2, price: 34.99 }, { name: "Vitamin C Cream", qty: 1, price: 22.50 }], total: 92.48, status: "processing", date: "2026-03-08", payment: "Credit Card", shipping: "DHL Express", address: "Bergmannstr. 14, 10961 Berlin" },
  { id: 1041, customer: "Tomás García", email: "tomas@example.com", items: [{ name: "Hair Growth Oil", qty: 1, price: 28.00 }], total: 28.00, status: "completed", date: "2026-03-07", payment: "PayPal", shipping: "Standard", address: "Calle Mayor 8, 28013 Madrid" },
  { id: 1040, customer: "Sophie Laurent", email: "sophie@example.com", items: [{ name: "Retinol Night Cream", qty: 1, price: 45.00 }, { name: "Eye Contour Gel", qty: 1, price: 19.99 }], total: 64.99, status: "on-hold", date: "2026-03-07", payment: "Bank Transfer", shipping: "DPD", address: "Rue de Rivoli 22, 75001 Paris" },
  { id: 1039, customer: "Marco Bianchi", email: "marco@example.com", items: [{ name: "Beard Oil Premium", qty: 3, price: 18.50 }], total: 55.50, status: "pending", date: "2026-03-06", payment: "Credit Card", shipping: "GLS", address: "Via Roma 45, 20121 Milano" },
  { id: 1038, customer: "Anna Kowalski", email: "anna@example.com", items: [{ name: "Shea Body Butter", qty: 2, price: 24.00 }, { name: "Lip Balm Set", qty: 1, price: 12.99 }], total: 60.99, status: "completed", date: "2026-03-06", payment: "Klarna", shipping: "Hermes", address: "Złota 59, 00-120 Warszawa" },
  { id: 1037, customer: "Erik Johansson", email: "erik@example.com", items: [{ name: "Anti-Aging Serum", qty: 1, price: 55.00 }], total: 55.00, status: "refunded", date: "2026-03-05", payment: "Credit Card", shipping: "PostNord", address: "Sveavägen 12, 111 57 Stockholm" },
  { id: 1036, customer: "Clara Hoffmann", email: "clara@example.com", items: [{ name: "Charcoal Face Mask", qty: 4, price: 15.00 }], total: 60.00, status: "processing", date: "2026-03-05", payment: "PayPal", shipping: "DHL Standard", address: "Kurfürstendamm 200, 10719 Berlin" },
  { id: 1035, customer: "Hugo Petit", email: "hugo@example.com", items: [{ name: "Aloe Vera Gel", qty: 2, price: 11.99 }, { name: "Sunscreen SPF50", qty: 1, price: 19.99 }], total: 43.97, status: "completed", date: "2026-03-04", payment: "Credit Card", shipping: "Colissimo", address: "Bd Haussmann 78, 75008 Paris" },
  { id: 1034, customer: "Mia Schneider", email: "mia@example.com", items: [{ name: "Rose Water Toner", qty: 1, price: 16.50 }], total: 16.50, status: "cancelled", date: "2026-03-04", payment: "Bank Transfer", shipping: "DHL", address: "Maximilianstr. 35, 80539 München" },
  { id: 1033, customer: "Jonas Fischer", email: "jonas@example.com", items: [{ name: "Hyaluronic Acid Serum", qty: 2, price: 29.99 }, { name: "Peptide Moisturizer", qty: 1, price: 38.00 }], total: 97.98, status: "processing", date: "2026-03-03", payment: "Credit Card", shipping: "DHL Express", address: "Friedrichstr. 101, 10117 Berlin" },
];

// ─── WooCommerce REST API v3 format (used by API routes) ─────────────────────
export const WC_MOCK_ORDERS = [
  {
    id: 1042, number: "1042", status: "processing", currency: "EUR",
    date_created: "2026-03-08T10:30:00", date_modified: "2026-03-08T11:00:00",
    total: "92.48", total_tax: "14.76",
    billing: { first_name: "Lena", last_name: "Müller", email: "lena@example.com", address_1: "Bergmannstr. 14", city: "Berlin", postcode: "10961", country: "DE" },
    shipping: { first_name: "Lena", last_name: "Müller", address_1: "Bergmannstr. 14", city: "Berlin", postcode: "10961", country: "DE" },
    line_items: [{ id: 1, name: "Organic Face Serum", quantity: 2, price: "34.99", sku: "OFS-001", subtotal: "69.98", total: "69.98" }, { id: 2, name: "Vitamin C Cream", quantity: 1, price: "22.50", sku: "VCC-002", subtotal: "22.50", total: "22.50" }],
    payment_method: "credit_card", payment_method_title: "Credit Card", customer_note: "",
  },
  {
    id: 1041, number: "1041", status: "completed", currency: "EUR",
    date_created: "2026-03-07T14:15:00", date_modified: "2026-03-07T16:00:00",
    total: "28.00", total_tax: "4.47",
    billing: { first_name: "Tomás", last_name: "García", email: "tomas@example.com", address_1: "Calle Mayor 8", city: "Madrid", postcode: "28013", country: "ES" },
    shipping: { first_name: "Tomás", last_name: "García", address_1: "Calle Mayor 8", city: "Madrid", postcode: "28013", country: "ES" },
    line_items: [{ id: 3, name: "Hair Growth Oil", quantity: 1, price: "28.00", sku: "HGO-003", subtotal: "28.00", total: "28.00" }],
    payment_method: "paypal", payment_method_title: "PayPal", customer_note: "",
  },
  {
    id: 1040, number: "1040", status: "on-hold", currency: "EUR",
    date_created: "2026-03-07T09:00:00", date_modified: "2026-03-07T09:30:00",
    total: "64.99", total_tax: "10.38",
    billing: { first_name: "Sophie", last_name: "Laurent", email: "sophie@example.com", address_1: "Rue de Rivoli 22", city: "Paris", postcode: "75001", country: "FR" },
    shipping: { first_name: "Sophie", last_name: "Laurent", address_1: "Rue de Rivoli 22", city: "Paris", postcode: "75001", country: "FR" },
    line_items: [{ id: 4, name: "Retinol Night Cream", quantity: 1, price: "45.00", sku: "RNC-004", subtotal: "45.00", total: "45.00" }, { id: 5, name: "Eye Contour Gel", quantity: 1, price: "19.99", sku: "ECG-005", subtotal: "19.99", total: "19.99" }],
    payment_method: "bacs", payment_method_title: "Bank Transfer", customer_note: "Please send tracking number",
  },
  {
    id: 1039, number: "1039", status: "pending", currency: "EUR",
    date_created: "2026-03-06T16:45:00", date_modified: "2026-03-06T16:45:00",
    total: "55.50", total_tax: "8.86",
    billing: { first_name: "Marco", last_name: "Bianchi", email: "marco@example.com", address_1: "Via Roma 45", city: "Milano", postcode: "20121", country: "IT" },
    shipping: { first_name: "Marco", last_name: "Bianchi", address_1: "Via Roma 45", city: "Milano", postcode: "20121", country: "IT" },
    line_items: [{ id: 6, name: "Beard Oil Premium", quantity: 3, price: "18.50", sku: "BOP-006", subtotal: "55.50", total: "55.50" }],
    payment_method: "credit_card", payment_method_title: "Credit Card", customer_note: "",
  },
  {
    id: 1038, number: "1038", status: "completed", currency: "EUR",
    date_created: "2026-03-06T11:20:00", date_modified: "2026-03-06T14:00:00",
    total: "60.99", total_tax: "9.74",
    billing: { first_name: "Anna", last_name: "Kowalski", email: "anna@example.com", address_1: "Złota 59", city: "Warszawa", postcode: "00-120", country: "PL" },
    shipping: { first_name: "Anna", last_name: "Kowalski", address_1: "Złota 59", city: "Warszawa", postcode: "00-120", country: "PL" },
    line_items: [{ id: 7, name: "Shea Body Butter", quantity: 2, price: "24.00", sku: "SBB-007", subtotal: "48.00", total: "48.00" }, { id: 8, name: "Lip Balm Set", quantity: 1, price: "12.99", sku: "LBS-008", subtotal: "12.99", total: "12.99" }],
    payment_method: "klarna", payment_method_title: "Klarna", customer_note: "",
  },
  {
    id: 1037, number: "1037", status: "refunded", currency: "EUR",
    date_created: "2026-03-05T08:00:00", date_modified: "2026-03-06T10:00:00",
    total: "55.00", total_tax: "8.78",
    billing: { first_name: "Erik", last_name: "Johansson", email: "erik@example.com", address_1: "Sveavägen 12", city: "Stockholm", postcode: "111 57", country: "SE" },
    shipping: { first_name: "Erik", last_name: "Johansson", address_1: "Sveavägen 12", city: "Stockholm", postcode: "111 57", country: "SE" },
    line_items: [{ id: 9, name: "Anti-Aging Serum", quantity: 1, price: "55.00", sku: "AAS-009", subtotal: "55.00", total: "55.00" }],
    payment_method: "credit_card", payment_method_title: "Credit Card", customer_note: "Product not as described",
  },
  {
    id: 1036, number: "1036", status: "processing", currency: "EUR",
    date_created: "2026-03-05T13:30:00", date_modified: "2026-03-05T14:00:00",
    total: "60.00", total_tax: "9.58",
    billing: { first_name: "Clara", last_name: "Hoffmann", email: "clara@example.com", address_1: "Kurfürstendamm 200", city: "Berlin", postcode: "10719", country: "DE" },
    shipping: { first_name: "Clara", last_name: "Hoffmann", address_1: "Kurfürstendamm 200", city: "Berlin", postcode: "10719", country: "DE" },
    line_items: [{ id: 10, name: "Charcoal Face Mask", quantity: 4, price: "15.00", sku: "CFM-010", subtotal: "60.00", total: "60.00" }],
    payment_method: "paypal", payment_method_title: "PayPal", customer_note: "",
  },
  {
    id: 1035, number: "1035", status: "completed", currency: "EUR",
    date_created: "2026-03-04T10:00:00", date_modified: "2026-03-04T12:00:00",
    total: "43.97", total_tax: "7.02",
    billing: { first_name: "Hugo", last_name: "Petit", email: "hugo@example.com", address_1: "Bd Haussmann 78", city: "Paris", postcode: "75008", country: "FR" },
    shipping: { first_name: "Hugo", last_name: "Petit", address_1: "Bd Haussmann 78", city: "Paris", postcode: "75008", country: "FR" },
    line_items: [{ id: 11, name: "Aloe Vera Gel", quantity: 2, price: "11.99", sku: "AVG-011", subtotal: "23.98", total: "23.98" }, { id: 12, name: "Sunscreen SPF50", quantity: 1, price: "19.99", sku: "SS50-012", subtotal: "19.99", total: "19.99" }],
    payment_method: "credit_card", payment_method_title: "Credit Card", customer_note: "",
  },
  {
    id: 1034, number: "1034", status: "cancelled", currency: "EUR",
    date_created: "2026-03-04T15:00:00", date_modified: "2026-03-04T16:00:00",
    total: "16.50", total_tax: "2.63",
    billing: { first_name: "Mia", last_name: "Schneider", email: "mia@example.com", address_1: "Maximilianstr. 35", city: "München", postcode: "80539", country: "DE" },
    shipping: { first_name: "Mia", last_name: "Schneider", address_1: "Maximilianstr. 35", city: "München", postcode: "80539", country: "DE" },
    line_items: [{ id: 13, name: "Rose Water Toner", quantity: 1, price: "16.50", sku: "RWT-013", subtotal: "16.50", total: "16.50" }],
    payment_method: "bacs", payment_method_title: "Bank Transfer", customer_note: "",
  },
  {
    id: 1033, number: "1033", status: "processing", currency: "EUR",
    date_created: "2026-03-03T09:15:00", date_modified: "2026-03-03T10:00:00",
    total: "97.98", total_tax: "15.65",
    billing: { first_name: "Jonas", last_name: "Fischer", email: "jonas@example.com", address_1: "Friedrichstr. 101", city: "Berlin", postcode: "10117", country: "DE" },
    shipping: { first_name: "Jonas", last_name: "Fischer", address_1: "Friedrichstr. 101", city: "Berlin", postcode: "10117", country: "DE" },
    line_items: [{ id: 14, name: "Hyaluronic Acid Serum", quantity: 2, price: "29.99", sku: "HAS-014", subtotal: "59.98", total: "59.98" }, { id: 15, name: "Peptide Moisturizer", quantity: 1, price: "38.00", sku: "PM-015", subtotal: "38.00", total: "38.00" }],
    payment_method: "credit_card", payment_method_title: "Credit Card", customer_note: "",
  },
  {
    id: 1032, number: "1032", status: "completed", currency: "EUR",
    date_created: "2026-03-02T14:00:00", date_modified: "2026-03-02T15:30:00",
    total: "78.50", total_tax: "12.53",
    billing: { first_name: "Ingrid", last_name: "Berg", email: "ingrid@example.com", address_1: "Karl Johans gate 5", city: "Oslo", postcode: "0154", country: "NO" },
    shipping: { first_name: "Ingrid", last_name: "Berg", address_1: "Karl Johans gate 5", city: "Oslo", postcode: "0154", country: "NO" },
    line_items: [{ id: 16, name: "Nordic Berry Serum", quantity: 2, price: "32.00", sku: "NBS-016", subtotal: "64.00", total: "64.00" }, { id: 17, name: "Collagen Booster", quantity: 1, price: "14.50", sku: "CB-017", subtotal: "14.50", total: "14.50" }],
    payment_method: "credit_card", payment_method_title: "Credit Card", customer_note: "",
  },
  {
    id: 1031, number: "1031", status: "pending", currency: "EUR",
    date_created: "2026-03-01T11:00:00", date_modified: "2026-03-01T11:00:00",
    total: "34.99", total_tax: "5.59",
    billing: { first_name: "Pieter", last_name: "Van Den Berg", email: "pieter@example.com", address_1: "Herengracht 100", city: "Amsterdam", postcode: "1015 BS", country: "NL" },
    shipping: { first_name: "Pieter", last_name: "Van Den Berg", address_1: "Herengracht 100", city: "Amsterdam", postcode: "1015 BS", country: "NL" },
    line_items: [{ id: 18, name: "Vitamin C Brightening Mask", quantity: 1, price: "34.99", sku: "VCM-018", subtotal: "34.99", total: "34.99" }],
    payment_method: "ideal", payment_method_title: "iDEAL", customer_note: "Gift wrap please",
  },
  {
    id: 1030, number: "1030", status: "on-hold", currency: "EUR",
    date_created: "2026-02-28T16:30:00", date_modified: "2026-02-28T17:00:00",
    total: "129.00", total_tax: "20.60",
    billing: { first_name: "Katarzyna", last_name: "Nowak", email: "kasia@example.com", address_1: "Marszałkowska 10", city: "Warszawa", postcode: "00-590", country: "PL" },
    shipping: { first_name: "Katarzyna", last_name: "Nowak", address_1: "Marszałkowska 10", city: "Warszawa", postcode: "00-590", country: "PL" },
    line_items: [{ id: 19, name: "Luxury Face Oil Set", quantity: 1, price: "89.00", sku: "LFO-019", subtotal: "89.00", total: "89.00" }, { id: 20, name: "Eye Cream Premium", quantity: 2, price: "20.00", sku: "ECP-020", subtotal: "40.00", total: "40.00" }],
    payment_method: "bacs", payment_method_title: "Bank Transfer", customer_note: "",
  },
  {
    id: 1029, number: "1029", status: "completed", currency: "EUR",
    date_created: "2026-02-27T09:00:00", date_modified: "2026-02-27T11:00:00",
    total: "45.00", total_tax: "7.19",
    billing: { first_name: "Lucas", last_name: "Dubois", email: "lucas@example.com", address_1: "Avenue des Champs 15", city: "Lyon", postcode: "69001", country: "FR" },
    shipping: { first_name: "Lucas", last_name: "Dubois", address_1: "Avenue des Champs 15", city: "Lyon", postcode: "69001", country: "FR" },
    line_items: [{ id: 21, name: "Micellar Cleansing Water", quantity: 3, price: "15.00", sku: "MCW-021", subtotal: "45.00", total: "45.00" }],
    payment_method: "credit_card", payment_method_title: "Credit Card", customer_note: "",
  },
  {
    id: 1028, number: "1028", status: "processing", currency: "EUR",
    date_created: "2026-02-26T13:45:00", date_modified: "2026-02-26T14:00:00",
    total: "67.48", total_tax: "10.78",
    billing: { first_name: "Amelie", last_name: "Weber", email: "amelie@example.com", address_1: "Schillerstr. 8", city: "Frankfurt", postcode: "60313", country: "DE" },
    shipping: { first_name: "Amelie", last_name: "Weber", address_1: "Schillerstr. 8", city: "Frankfurt", postcode: "60313", country: "DE" },
    line_items: [{ id: 22, name: "Niacinamide Serum", quantity: 1, price: "29.99", sku: "NS-022", subtotal: "29.99", total: "29.99" }, { id: 23, name: "Gentle Foaming Cleanser", quantity: 2, price: "18.75", sku: "GFC-023", subtotal: "37.50", total: "37.50" }],
    payment_method: "paypal", payment_method_title: "PayPal", customer_note: "No plastic packaging",
  },
];

export const WC_MOCK_PRODUCTS = [
  { id: 1, name: "Organic Face Serum", sku: "OFS-001", price: "34.99", regular_price: "39.99", stock_quantity: 45, stock_status: "instock", categories: [{ id: 1, name: "Serums" }], images: [] },
  { id: 2, name: "Vitamin C Cream", sku: "VCC-002", price: "22.50", regular_price: "22.50", stock_quantity: 30, stock_status: "instock", categories: [{ id: 2, name: "Moisturisers" }], images: [] },
  { id: 3, name: "Hair Growth Oil", sku: "HGO-003", price: "28.00", regular_price: "32.00", stock_quantity: 0, stock_status: "outofstock", categories: [{ id: 3, name: "Hair Care" }], images: [] },
  { id: 4, name: "Retinol Night Cream", sku: "RNC-004", price: "45.00", regular_price: "45.00", stock_quantity: 18, stock_status: "instock", categories: [{ id: 2, name: "Moisturisers" }], images: [] },
  { id: 5, name: "Eye Contour Gel", sku: "ECG-005", price: "19.99", regular_price: "24.99", stock_quantity: 60, stock_status: "instock", categories: [{ id: 4, name: "Eye Care" }], images: [] },
  { id: 6, name: "Beard Oil Premium", sku: "BOP-006", price: "18.50", regular_price: "18.50", stock_quantity: 25, stock_status: "instock", categories: [{ id: 5, name: "Men's Care" }], images: [] },
  { id: 7, name: "Shea Body Butter", sku: "SBB-007", price: "24.00", regular_price: "24.00", stock_quantity: 40, stock_status: "instock", categories: [{ id: 6, name: "Body Care" }], images: [] },
  { id: 8, name: "Charcoal Face Mask", sku: "CFM-010", price: "15.00", regular_price: "15.00", stock_quantity: 8, stock_status: "instock", categories: [{ id: 7, name: "Masks" }], images: [] },
  { id: 9, name: "Anti-Aging Serum", sku: "AAS-009", price: "55.00", regular_price: "65.00", stock_quantity: 12, stock_status: "instock", categories: [{ id: 1, name: "Serums" }], images: [] },
  { id: 10, name: "Hyaluronic Acid Serum", sku: "HAS-014", price: "29.99", regular_price: "29.99", stock_quantity: 55, stock_status: "instock", categories: [{ id: 1, name: "Serums" }], images: [] },
];

export const WC_MOCK_CUSTOMERS = [
  { id: 1, first_name: "Lena", last_name: "Müller", email: "lena@example.com", billing: { city: "Berlin", country: "DE" }, orders_count: 3, total_spent: "245.00" },
  { id: 2, first_name: "Tomás", last_name: "García", email: "tomas@example.com", billing: { city: "Madrid", country: "ES" }, orders_count: 1, total_spent: "28.00" },
  { id: 3, first_name: "Sophie", last_name: "Laurent", email: "sophie@example.com", billing: { city: "Paris", country: "FR" }, orders_count: 2, total_spent: "108.96" },
  { id: 4, first_name: "Marco", last_name: "Bianchi", email: "marco@example.com", billing: { city: "Milano", country: "IT" }, orders_count: 1, total_spent: "55.50" },
  { id: 5, first_name: "Anna", last_name: "Kowalski", email: "anna@example.com", billing: { city: "Warszawa", country: "PL" }, orders_count: 2, total_spent: "190.99" },
  { id: 6, first_name: "Erik", last_name: "Johansson", email: "erik@example.com", billing: { city: "Stockholm", country: "SE" }, orders_count: 1, total_spent: "55.00" },
  { id: 7, first_name: "Clara", last_name: "Hoffmann", email: "clara@example.com", billing: { city: "Berlin", country: "DE" }, orders_count: 4, total_spent: "310.00" },
  { id: 8, first_name: "Jonas", last_name: "Fischer", email: "jonas@example.com", billing: { city: "Berlin", country: "DE" }, orders_count: 2, total_spent: "195.96" },
];
